#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend localhost
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 11562-web-01 52.3.220.120:80
        server 11562-web-02 54.145.79.115:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
